name: Actions Release
on:
  push:
    branches:
    - master
jobs:

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10]

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        env
        npm install -g npminstall
        npminstall

    - name: Continuous integration
      run: |
        npm run ci

    - name: Code Coverage
      run: |
        npm install codecov -g
        codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Release NPN Package
      run: npm run semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
